// // event.types.ts
// export type EventItem = {
//   id: string;
//   companyId: string;
//   title: string;
//   description: string;
//   format: string;
//   category: string;
//   bannerUrl: string | null;
//   posterUrl: string | null;
//   placeName: string;
//   placeAddress: string | null;
//   googleMapsUrl: string | null;
//   googlePlaceId: string | null;
//   placeLat: number | null;
//   placeLng: number | null;
//   startsAt: string;
//   endsAt: string;
//   publishedAt: string;
//   price: string;
//   ticketsLimit: number;
//   visitorsVisibility: string;
//   status: string;
//   createdAt: string;
//   updatedAt: string;
// };
export type EventItem = {
  id: string;
  companyId: string;
  title: string;
  description: string;
  format: string;
  category: string;
  bannerUrl: string | null;
  posterUrl: string | null;
  placeName: string;
  placeAddress: string | null;
  googleMapsUrl: string | null;
  googlePlaceId: string | null;
  placeLat: string | number | null;
  placeLng: string | number | null;
  startsAt: string;
  endsAt: string;
  publishedAt: string;
  price: string;
  ticketsLimit: number;
  visitorsVisibility: string;
  notifyOnNewVisitor?: boolean;
  status: string;
  createdAt: string;
  updatedAt: string;
};
